"""fix relationship

Revision ID: 04d11ab162bf
Revises: 1fa0fe7f5983
Create Date: 2023-07-18 12:09:01.083904

"""
from alembic import op  # type: ignore
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "04d11ab162bf"
down_revision = "1fa0fe7f5983"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
