"""init

Revision ID: 1f7fa1d25b8d
Revises: 
Create Date: 2023-07-06 18:08:12.895857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f7fa1d25b8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('neural_models',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uploaded_images',
    sa.Column('file_unique_id', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('responses',
    sa.Column('response_image_id', sa.String(), nullable=True),
    sa.Column('generated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('uploaded_image_id', sa.Uuid(), nullable=False),
    sa.Column('model_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['neural_models.id'], ),
    sa.ForeignKeyConstraint(['uploaded_image_id'], ['uploaded_images.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('response_image_id', 'uploaded_image_id', 'model_id')
    )
    op.create_table('recognized_objects',
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['response_id'], ['responses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recognized_objects')
    op.drop_table('responses')
    op.drop_table('uploaded_images')
    op.drop_table('neural_models')
    # ### end Alembic commands ###
