"""fix relationship

Revision ID: 3d0d4d1c1b3f
Revises: 04d11ab162bf
Create Date: 2023-07-18 12:10:19.910458

"""
from alembic import op  # type: ignore
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3d0d4d1c1b3f"
down_revision = "04d11ab162bf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
