"""FK relations

Revision ID: 4d4c4e87a698
Revises: 1f7fa1d25b8d
Create Date: 2023-07-14 21:21:50.212979

"""
from alembic import op  # type: ignore[attr-defined]
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4d4c4e87a698"
down_revision = "1f7fa1d25b8d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "recognized_objects_response_id_fkey", "recognized_objects", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "recognized_objects",
        "responses",
        ["response_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "responses_uploaded_image_id_fkey", "responses", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "responses",
        "uploaded_images",
        ["uploaded_image_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "responses", type_="foreignkey")
    op.create_foreign_key(
        "responses_uploaded_image_id_fkey",
        "responses",
        "uploaded_images",
        ["uploaded_image_id"],
        ["id"],
    )
    op.drop_constraint(None, "recognized_objects", type_="foreignkey")
    op.create_foreign_key(
        "recognized_objects_response_id_fkey",
        "recognized_objects",
        "responses",
        ["response_id"],
        ["id"],
    )
    # ### end Alembic commands ###
