name: ruff
run-name: ${{ github.actor }} ruff code checking
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest pytest-asyncio
      - name: Run ruff
        run: ruff check --format=github --select E,F,D --ignore D100,D104,D105,D107,F821 bot
      - name: Run tests
        run: pytest
